# Generated by Django 4.2.2 on 2023-06-09 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 9, 18, 41, 22, 392656)
            ),
        ),
        
    ]
    
