# Generated by Django 4.2.2 on 2023-06-16 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapapp", "0002_alter_contact_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="addUser",
        ),
        migrations.RenameField(
            model_name="adduser",
            old_name="passwoed",
            new_name="password",
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 16, 20, 41, 45, 607104)
            ),
        ),
    ]
