# Generated by Django 4.2.2 on 2023-06-18 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lapapp", "0004_alter_contact_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 18, 23, 9, 32, 691020)
            ),
        ),
    ]
